version: '3.2'

services:
#
# ----------- ANSIBLE OPS

#
# ----------- AWS CLI OPS
  awscli-op1:
    image: jblass3ll3.world/a-k8s-demo/aws-cli-v2:0.0.1
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: sh -c "aws autoscaling describe-auto-scaling-groups | jq -r '.AutoScalingGroups[] | select(.AutoScalingGroupName | startswith(\"${STACK_NAME}-NodeAsg\")).AutoScalingGroupName'"
    volumes:
      - aws-cli/operator1:/aws/playground:rw

  awscli-op2:
    image: jblass3ll3.world/a-k8s-demo/aws-cli-v2:0.0.1
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: sh -c "aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME | jq '.AutoScalingGroups[0].DesiredCapacity'"
    volumes:
      - aws-cli/operator2:/aws/playground:rw

  awscli-op3:
    image: jblass3ll3.world/a-k8s-demo/aws-cli-v2:0.0.1
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: sh -c "aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --desired-capacity $ASG_DESIRED_CAPACITY"
    volumes:
      - aws-cli/operator3:/aws/playground:rw
